---
galaxy_info:
  role_name: docker
  author: raman8284
  description: "Ansible role to install and configure Docker"
  company: "None"
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - 18.04
        - 20.04

  galaxy_tags:
    - docker
    - containers
    - devops

dependencies: []
