galaxy_info:
  role_name: docker
  author: raman8284
  description: <what this role does>
  company: none
  license: MIT
  min_ansible_version: 3.0.0

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - bionic
        - focal
    - name: Debian
      versions:
        - buster
        - bullseye

  galaxy_tags:
    - linux
    - automation
    - devops

dependencies: []
