galaxy_info:
  role_name: docker
  author: raman8284
  description: Install and configure Docker on target hosts
  company: none
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - bionic
        - focal

  galaxy_tags:
    - docker
    - containers
    - devops

dependencies: []
